# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: acs1.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aelf import options_pb2 as aelf_dot_options__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from aelf import core_pb2 as aelf_dot_core__pb2
import authority_info_pb2 as authority__info__pb2

from aelf.options_pb2 import *
from google.protobuf.empty_pb2 import *
from google.protobuf.wrappers_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nacs1.proto\x12\x04\x61\x63s1\x1a\x12\x61\x65lf/options.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x0f\x61\x65lf/core.proto\x1a\x14\x61uthority_info.proto\"Z\n\nMethodFees\x12\x13\n\x0bmethod_name\x18\x01 \x01(\t\x12\x1d\n\x04\x66\x65\x65s\x18\x02 \x03(\x0b\x32\x0f.acs1.MethodFee\x12\x18\n\x10is_size_fee_free\x18\x03 \x01(\x08\".\n\tMethodFee\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x11\n\tbasic_fee\x18\x02 \x01(\x03\x32\xae\x02\n\x19MethodFeeProviderContract\x12:\n\x0cSetMethodFee\x12\x10.acs1.MethodFees\x1a\x16.google.protobuf.Empty\"\x00\x12\x45\n\x19\x43hangeMethodFeeController\x12\x0e.AuthorityInfo\x1a\x16.google.protobuf.Empty\"\x00\x12\x45\n\x0cGetMethodFee\x12\x1c.google.protobuf.StringValue\x1a\x10.acs1.MethodFees\"\x05\x88\x89\xf7\x01\x01\x12G\n\x16GetMethodFeeController\x12\x16.google.protobuf.Empty\x1a\x0e.AuthorityInfo\"\x05\x88\x89\xf7\x01\x01\x42\x1f\xaa\x02\x13\x41\x45lf.Standards.ACS1\x8a\x92\xf4\x01\x04\x61\x63s1P\x00P\x01P\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'acs1_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\023AElf.Standards.ACS1\212\222\364\001\004acs1'
  _METHODFEEPROVIDERCONTRACT.methods_by_name['GetMethodFee']._options = None
  _METHODFEEPROVIDERCONTRACT.methods_by_name['GetMethodFee']._serialized_options = b'\210\211\367\001\001'
  _METHODFEEPROVIDERCONTRACT.methods_by_name['GetMethodFeeController']._options = None
  _METHODFEEPROVIDERCONTRACT.methods_by_name['GetMethodFeeController']._serialized_options = b'\210\211\367\001\001'
  _METHODFEES._serialized_start=140
  _METHODFEES._serialized_end=230
  _METHODFEE._serialized_start=232
  _METHODFEE._serialized_end=278
  _METHODFEEPROVIDERCONTRACT._serialized_start=281
  _METHODFEEPROVIDERCONTRACT._serialized_end=583
# @@protoc_insertion_point(module_scope)
