# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: acs11.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aelf import options_pb2 as aelf_dot_options__pb2
from aelf import core_pb2 as aelf_dot_core__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61\x63s11.proto\x12\x05\x61\x63s11\x1a\x12\x61\x65lf/options.proto\x1a\x0f\x61\x65lf/core.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto2\xb6\x02\n\x1d\x43rossChainInteractionContract\x12X\n\x1fUpdateInformationFromCrossChain\x12\x1b.google.protobuf.BytesValue\x1a\x16.google.protobuf.Empty\"\x00\x12\x64\n!GetChainInitializationInformation\x12\x1b.google.protobuf.BytesValue\x1a\x1b.google.protobuf.BytesValue\"\x05\x88\x89\xf7\x01\x01\x12U\n!CheckCrossChainIndexingPermission\x12\r.aelf.Address\x1a\x1a.google.protobuf.BoolValue\"\x05\x88\x89\xf7\x01\x01\x42!\xaa\x02\x14\x41\x45lf.Standards.ACS11\x8a\x92\xf4\x01\x05\x61\x63s11b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'acs11_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\024AElf.Standards.ACS11\212\222\364\001\005acs11'
  _CROSSCHAININTERACTIONCONTRACT.methods_by_name['GetChainInitializationInformation']._options = None
  _CROSSCHAININTERACTIONCONTRACT.methods_by_name['GetChainInitializationInformation']._serialized_options = b'\210\211\367\001\001'
  _CROSSCHAININTERACTIONCONTRACT.methods_by_name['CheckCrossChainIndexingPermission']._options = None
  _CROSSCHAININTERACTIONCONTRACT.methods_by_name['CheckCrossChainIndexingPermission']._serialized_options = b'\210\211\367\001\001'
  _CROSSCHAININTERACTIONCONTRACT._serialized_start=121
  _CROSSCHAININTERACTIONCONTRACT._serialized_end=431
# @@protoc_insertion_point(module_scope)
