# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: acs10.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aelf import options_pb2 as aelf_dot_options__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from aelf import core_pb2 as aelf_dot_core__pb2

from aelf.options_pb2 import *
from google.protobuf.empty_pb2 import *
from google.protobuf.wrappers_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61\x63s10.proto\x12\x05\x61\x63s10\x1a\x12\x61\x65lf/options.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x0f\x61\x65lf/core.proto\"-\n\x0b\x44onateInput\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x03\"%\n\x0cReleaseInput\x12\x15\n\rperiod_number\x18\x01 \x01(\x03\"\x1b\n\nSymbolList\x12\r\n\x05value\x18\x01 \x03(\t\"e\n\tDividends\x12*\n\x05value\x18\x01 \x03(\x0b\x32\x1b.acs10.Dividends.ValueEntry\x1a,\n\nValueEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x03:\x02\x38\x01\"{\n\x10\x44onationReceived\x12\x1b\n\x04\x66rom\x18\x01 \x01(\x0b\x32\r.aelf.Address\x12$\n\rpool_contract\x18\x02 \x01(\x0b\x32\r.aelf.Address\x12\x0e\n\x06symbol\x18\x03 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x03:\x04\xa0\xbb\x18\x01\x32\x9d\x03\n\x14\x44ividendPoolContract\x12\x36\n\x06\x44onate\x12\x12.acs10.DonateInput\x1a\x16.google.protobuf.Empty\"\x00\x12\x38\n\x07Release\x12\x13.acs10.ReleaseInput\x1a\x16.google.protobuf.Empty\"\x00\x12<\n\rSetSymbolList\x12\x11.acs10.SymbolList\x1a\x16.google.protobuf.Empty\"\x00\x12\x41\n\rGetSymbolList\x12\x16.google.protobuf.Empty\x1a\x11.acs10.SymbolList\"\x05\x88\x89\xf7\x01\x01\x12L\n\x19GetUndistributedDividends\x12\x16.google.protobuf.Empty\x1a\x10.acs10.Dividends\"\x05\x88\x89\xf7\x01\x01\x12\x44\n\x0cGetDividends\x12\x1b.google.protobuf.Int64Value\x1a\x10.acs10.Dividends\"\x05\x88\x89\xf7\x01\x01\x42!\xaa\x02\x14\x41\x45lf.Standards.ACS10\x8a\x92\xf4\x01\x05\x61\x63s10P\x00P\x01P\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'acs10_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\024AElf.Standards.ACS10\212\222\364\001\005acs10'
  _DIVIDENDS_VALUEENTRY._options = None
  _DIVIDENDS_VALUEENTRY._serialized_options = b'8\001'
  _DONATIONRECEIVED._options = None
  _DONATIONRECEIVED._serialized_options = b'\240\273\030\001'
  _DIVIDENDPOOLCONTRACT.methods_by_name['GetSymbolList']._options = None
  _DIVIDENDPOOLCONTRACT.methods_by_name['GetSymbolList']._serialized_options = b'\210\211\367\001\001'
  _DIVIDENDPOOLCONTRACT.methods_by_name['GetUndistributedDividends']._options = None
  _DIVIDENDPOOLCONTRACT.methods_by_name['GetUndistributedDividends']._serialized_options = b'\210\211\367\001\001'
  _DIVIDENDPOOLCONTRACT.methods_by_name['GetDividends']._options = None
  _DIVIDENDPOOLCONTRACT.methods_by_name['GetDividends']._serialized_options = b'\210\211\367\001\001'
  _DONATEINPUT._serialized_start=120
  _DONATEINPUT._serialized_end=165
  _RELEASEINPUT._serialized_start=167
  _RELEASEINPUT._serialized_end=204
  _SYMBOLLIST._serialized_start=206
  _SYMBOLLIST._serialized_end=233
  _DIVIDENDS._serialized_start=235
  _DIVIDENDS._serialized_end=336
  _DIVIDENDS_VALUEENTRY._serialized_start=292
  _DIVIDENDS_VALUEENTRY._serialized_end=336
  _DONATIONRECEIVED._serialized_start=338
  _DONATIONRECEIVED._serialized_end=461
  _DIVIDENDPOOLCONTRACT._serialized_start=464
  _DIVIDENDPOOLCONTRACT._serialized_end=877
# @@protoc_insertion_point(module_scope)
