# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: acs2.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aelf import core_pb2 as aelf_dot_core__pb2
from aelf import options_pb2 as aelf_dot_options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nacs2.proto\x12\x04\x61\x63s2\x1a\x0f\x61\x65lf/core.proto\x1a\x12\x61\x65lf/options.proto\"\x81\x01\n\x0cResourceInfo\x12*\n\x0bwrite_paths\x18\x01 \x03(\x0b\x32\x15.aelf.ScopedStatePath\x12)\n\nread_paths\x18\x02 \x03(\x0b\x32\x15.aelf.ScopedStatePath\x12\x1a\n\x12non_parallelizable\x18\x03 \x01(\x08\x32K\n\x08\x41\x43S2Base\x12?\n\x0fGetResourceInfo\x12\x11.aelf.Transaction\x1a\x12.acs2.ResourceInfo\"\x05\x88\x89\xf7\x01\x01\x42\x1f\xaa\x02\x13\x41\x45lf.Standards.ACS2\x8a\x92\xf4\x01\x04\x61\x63s2b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'acs2_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\023AElf.Standards.ACS2\212\222\364\001\004acs2'
  _ACS2BASE.methods_by_name['GetResourceInfo']._options = None
  _ACS2BASE.methods_by_name['GetResourceInfo']._serialized_options = b'\210\211\367\001\001'
  _RESOURCEINFO._serialized_start=58
  _RESOURCEINFO._serialized_end=187
  _ACS2BASE._serialized_start=189
  _ACS2BASE._serialized_end=264
# @@protoc_insertion_point(module_scope)
