# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: acs4.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aelf import options_pb2 as aelf_dot_options__pb2
from aelf import core_pb2 as aelf_dot_core__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nacs4.proto\x12\x04\x61\x63s4\x1a\x12\x61\x65lf/options.proto\x1a\x0f\x61\x65lf/core.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbb\x01\n\x10\x43onsensusCommand\x12*\n\"limit_milliseconds_of_mining_block\x18\x01 \x01(\x05\x12\x0c\n\x04hint\x18\x02 \x01(\x0c\x12\x38\n\x14\x61rranged_mining_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x33\n\x0fmining_due_time\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"K\n\x10ValidationResult\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x15\n\ris_re_trigger\x18\x03 \x01(\x08\":\n\x0fTransactionList\x12\'\n\x0ctransactions\x18\x01 \x03(\x0b\x32\x11.aelf.Transaction2\xdb\x03\n\x11\x43onsensusContract\x12Q\n\x13GetConsensusCommand\x12\x1b.google.protobuf.BytesValue\x1a\x16.acs4.ConsensusCommand\"\x05\x88\x89\xf7\x01\x01\x12X\n\x15GetConsensusExtraData\x12\x1b.google.protobuf.BytesValue\x1a\x1b.google.protobuf.BytesValue\"\x05\x88\x89\xf7\x01\x01\x12Z\n\x1dGenerateConsensusTransactions\x12\x1b.google.protobuf.BytesValue\x1a\x15.acs4.TransactionList\"\x05\x88\x89\xf7\x01\x01\x12^\n ValidateConsensusBeforeExecution\x12\x1b.google.protobuf.BytesValue\x1a\x16.acs4.ValidationResult\"\x05\x88\x89\xf7\x01\x01\x12]\n\x1fValidateConsensusAfterExecution\x12\x1b.google.protobuf.BytesValue\x1a\x16.acs4.ValidationResult\"\x05\x88\x89\xf7\x01\x01\x42\x1f\xaa\x02\x13\x41\x45lf.Standards.ACS4\x8a\x92\xf4\x01\x04\x61\x63s4b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'acs4_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\023AElf.Standards.ACS4\212\222\364\001\004acs4'
  _CONSENSUSCONTRACT.methods_by_name['GetConsensusCommand']._options = None
  _CONSENSUSCONTRACT.methods_by_name['GetConsensusCommand']._serialized_options = b'\210\211\367\001\001'
  _CONSENSUSCONTRACT.methods_by_name['GetConsensusExtraData']._options = None
  _CONSENSUSCONTRACT.methods_by_name['GetConsensusExtraData']._serialized_options = b'\210\211\367\001\001'
  _CONSENSUSCONTRACT.methods_by_name['GenerateConsensusTransactions']._options = None
  _CONSENSUSCONTRACT.methods_by_name['GenerateConsensusTransactions']._serialized_options = b'\210\211\367\001\001'
  _CONSENSUSCONTRACT.methods_by_name['ValidateConsensusBeforeExecution']._options = None
  _CONSENSUSCONTRACT.methods_by_name['ValidateConsensusBeforeExecution']._serialized_options = b'\210\211\367\001\001'
  _CONSENSUSCONTRACT.methods_by_name['ValidateConsensusAfterExecution']._options = None
  _CONSENSUSCONTRACT.methods_by_name['ValidateConsensusAfterExecution']._serialized_options = b'\210\211\367\001\001'
  _CONSENSUSCOMMAND._serialized_start=123
  _CONSENSUSCOMMAND._serialized_end=310
  _VALIDATIONRESULT._serialized_start=312
  _VALIDATIONRESULT._serialized_end=387
  _TRANSACTIONLIST._serialized_start=389
  _TRANSACTIONLIST._serialized_end=447
  _CONSENSUSCONTRACT._serialized_start=450
  _CONSENSUSCONTRACT._serialized_end=925
# @@protoc_insertion_point(module_scope)
