# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: acs5.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aelf import options_pb2 as aelf_dot_options__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nacs5.proto\x12\x04\x61\x63s5\x1a\x12\x61\x65lf/options.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xd3\x01\n\x16MethodCallingThreshold\x12J\n\x10symbol_to_amount\x18\x01 \x03(\x0b\x32\x30.acs5.MethodCallingThreshold.SymbolToAmountEntry\x12\x36\n\x14threshold_check_type\x18\x02 \x01(\x0e\x32\x18.acs5.ThresholdCheckType\x1a\x35\n\x13SymbolToAmountEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x03:\x02\x38\x01\"\xf3\x01\n\x1eSetMethodCallingThresholdInput\x12\x0e\n\x06method\x18\x01 \x01(\t\x12R\n\x10symbol_to_amount\x18\x02 \x03(\x0b\x32\x38.acs5.SetMethodCallingThresholdInput.SymbolToAmountEntry\x12\x36\n\x14threshold_check_type\x18\x03 \x01(\x0e\x32\x18.acs5.ThresholdCheckType\x1a\x35\n\x13SymbolToAmountEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x03:\x02\x38\x01*0\n\x12ThresholdCheckType\x12\x0b\n\x07\x42\x41LANCE\x10\x00\x12\r\n\tALLOWANCE\x10\x01\x32\xd7\x01\n\x18ThresholdSettingContract\x12[\n\x19SetMethodCallingThreshold\x12$.acs5.SetMethodCallingThresholdInput\x1a\x16.google.protobuf.Empty\"\x00\x12^\n\x19GetMethodCallingThreshold\x12\x1c.google.protobuf.StringValue\x1a\x1c.acs5.MethodCallingThreshold\"\x05\x88\x89\xf7\x01\x01\x42\x1f\xaa\x02\x13\x41\x45lf.Standards.ACS5\x8a\x92\xf4\x01\x04\x61\x63s5b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'acs5_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\023AElf.Standards.ACS5\212\222\364\001\004acs5'
  _METHODCALLINGTHRESHOLD_SYMBOLTOAMOUNTENTRY._options = None
  _METHODCALLINGTHRESHOLD_SYMBOLTOAMOUNTENTRY._serialized_options = b'8\001'
  _SETMETHODCALLINGTHRESHOLDINPUT_SYMBOLTOAMOUNTENTRY._options = None
  _SETMETHODCALLINGTHRESHOLDINPUT_SYMBOLTOAMOUNTENTRY._serialized_options = b'8\001'
  _THRESHOLDSETTINGCONTRACT.methods_by_name['GetMethodCallingThreshold']._options = None
  _THRESHOLDSETTINGCONTRACT.methods_by_name['GetMethodCallingThreshold']._serialized_options = b'\210\211\367\001\001'
  _THRESHOLDCHECKTYPE._serialized_start=561
  _THRESHOLDCHECKTYPE._serialized_end=609
  _METHODCALLINGTHRESHOLD._serialized_start=102
  _METHODCALLINGTHRESHOLD._serialized_end=313
  _METHODCALLINGTHRESHOLD_SYMBOLTOAMOUNTENTRY._serialized_start=260
  _METHODCALLINGTHRESHOLD_SYMBOLTOAMOUNTENTRY._serialized_end=313
  _SETMETHODCALLINGTHRESHOLDINPUT._serialized_start=316
  _SETMETHODCALLINGTHRESHOLDINPUT._serialized_end=559
  _SETMETHODCALLINGTHRESHOLDINPUT_SYMBOLTOAMOUNTENTRY._serialized_start=260
  _SETMETHODCALLINGTHRESHOLDINPUT_SYMBOLTOAMOUNTENTRY._serialized_end=313
  _THRESHOLDSETTINGCONTRACT._serialized_start=612
  _THRESHOLDSETTINGCONTRACT._serialized_end=827
# @@protoc_insertion_point(module_scope)
