# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: acs6.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aelf import options_pb2 as aelf_dot_options__pb2
from aelf import core_pb2 as aelf_dot_core__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nacs6.proto\x12\x04\x61\x63s6\x1a\x12\x61\x65lf/options.proto\x1a\x0f\x61\x65lf/core.proto\x1a\x1egoogle/protobuf/wrappers.proto2q\n\x1cRandomNumberProviderContract\x12Q\n\x0eGetRandomBytes\x12\x1b.google.protobuf.BytesValue\x1a\x1b.google.protobuf.BytesValue\"\x05\x88\x89\xf7\x01\x01\x42\x1f\xaa\x02\x13\x41\x45lf.Standards.ACS6\x8a\x92\xf4\x01\x04\x61\x63s6b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'acs6_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\023AElf.Standards.ACS6\212\222\364\001\004acs6'
  _RANDOMNUMBERPROVIDERCONTRACT.methods_by_name['GetRandomBytes']._options = None
  _RANDOMNUMBERPROVIDERCONTRACT.methods_by_name['GetRandomBytes']._serialized_options = b'\210\211\367\001\001'
  _RANDOMNUMBERPROVIDERCONTRACT._serialized_start=89
  _RANDOMNUMBERPROVIDERCONTRACT._serialized_end=202
# @@protoc_insertion_point(module_scope)
