# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: acs9.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aelf import options_pb2 as aelf_dot_options__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

from aelf.options_pb2 import *
from google.protobuf.empty_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nacs9.proto\x12\x04\x61\x63s9\x1a\x12\x61\x65lf/options.proto\x1a\x1bgoogle/protobuf/empty.proto\":\n\x18TakeContractProfitsInput\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x03\"s\n\x0cProfitConfig\x12\"\n\x1a\x64onation_parts_per_hundred\x18\x01 \x01(\x05\x12!\n\x19profits_token_symbol_list\x18\x02 \x03(\t\x12\x1c\n\x14staking_token_symbol\x18\x03 \x01(\t\"f\n\nProfitsMap\x12*\n\x05value\x18\x01 \x03(\x0b\x32\x1b.acs9.ProfitsMap.ValueEntry\x1a,\n\nValueEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x03:\x02\x38\x01\x32\xf5\x01\n\x17\x43ontractProfitsContract\x12O\n\x13TakeContractProfits\x12\x1e.acs9.TakeContractProfitsInput\x1a\x16.google.protobuf.Empty\"\x00\x12\x44\n\x0fGetProfitConfig\x12\x16.google.protobuf.Empty\x1a\x12.acs9.ProfitConfig\"\x05\x88\x89\xf7\x01\x01\x12\x43\n\x10GetProfitsAmount\x12\x16.google.protobuf.Empty\x1a\x10.acs9.ProfitsMap\"\x05\x88\x89\xf7\x01\x01\x42\x1f\xaa\x02\x13\x41\x45lf.Standards.ACS9\x8a\x92\xf4\x01\x04\x61\x63s9P\x00P\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'acs9_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\023AElf.Standards.ACS9\212\222\364\001\004acs9'
  _PROFITSMAP_VALUEENTRY._options = None
  _PROFITSMAP_VALUEENTRY._serialized_options = b'8\001'
  _CONTRACTPROFITSCONTRACT.methods_by_name['GetProfitConfig']._options = None
  _CONTRACTPROFITSCONTRACT.methods_by_name['GetProfitConfig']._serialized_options = b'\210\211\367\001\001'
  _CONTRACTPROFITSCONTRACT.methods_by_name['GetProfitsAmount']._options = None
  _CONTRACTPROFITSCONTRACT.methods_by_name['GetProfitsAmount']._serialized_options = b'\210\211\367\001\001'
  _TAKECONTRACTPROFITSINPUT._serialized_start=69
  _TAKECONTRACTPROFITSINPUT._serialized_end=127
  _PROFITCONFIG._serialized_start=129
  _PROFITCONFIG._serialized_end=244
  _PROFITSMAP._serialized_start=246
  _PROFITSMAP._serialized_end=348
  _PROFITSMAP_VALUEENTRY._serialized_start=304
  _PROFITSMAP_VALUEENTRY._serialized_end=348
  _CONTRACTPROFITSCONTRACT._serialized_start=351
  _CONTRACTPROFITSCONTRACT._serialized_end=596
# @@protoc_insertion_point(module_scope)
