# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authority_info.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aelf import core_pb2 as aelf_dot_core__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61uthority_info.proto\x1a\x0f\x61\x65lf/core.proto\"^\n\rAuthorityInfo\x12\'\n\x10\x63ontract_address\x18\x01 \x01(\x0b\x32\r.aelf.Address\x12$\n\rowner_address\x18\x02 \x01(\x0b\x32\r.aelf.Addressb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'authority_info_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AUTHORITYINFO._serialized_start=41
  _AUTHORITYINFO._serialized_end=135
# @@protoc_insertion_point(module_scope)
